add doi argument
clelange/cernopendata-client-go-old pull request #8
Opened 2021-10-12 19:55 UTC by florianl

Signed-off-by: Florian Lehner <dev@der-flo.net>

Add the option to provide a DOI instead of a record ID.

Example:
```
./main list -d 10.7483/OPENDATA.CMS.A342.9982
```

2021-10-19 16:13 UTC, florianl commented
hey @clelange :wave: 
can I get feedback on this PR?

2021-10-19 16:40 UTC, clelange commented
Hi @florianl - sorry about the delay. I've had a brief look, and in principle this looks good to me and is a welcomed addition. However, my code (and yours) doesn't have any tests, so the only way for me to check that it's working is to check out your PR and test it manually... I'll get to it some time later this week, maybe even tomorrow.

I'd of course appreciate very much if you implemented some tests, e.g. similar to what's done at:
- https://github.com/cernopendata/cernopendata-client/blob/master/tests/test_cli_download_files.py#L35
- https://github.com/cernopendata/cernopendata-client/blob/master/tests/test_cli_get_file_locations.py#L58
- https://github.com/cernopendata/cernopendata-client/blob/master/tests/test_cli_get_metadata.py#L38

These tests could also come in a separate PR, anything is appreciated 😃

2021-10-20 12:51 UTC, clelange commented
Your example fails for me:

```
./cernopendata-client-go list -d 10.7483/OPENDATA.CMS.A342.9982
http://opendata.cern.ch/api/records?page=1&q=doi%3A%2210.7483%2FOPENDATA.CMS.A342.9982%22&size=1
Error: failed to get recordID from doi: recordID needs to be positive integer number
```

Can you please check what's wrong?

2021-10-20 12:52 UTC, clelange requested changes

2021-10-20 12:52 UTC, clelange commented on cmd/root.go
> +	fmt.Println(queryURL)
Please remove debug statement.

2021-10-20 18:35 UTC, florianl commented on cmd/root.go
> +	fmt.Println(queryURL)
my fault :see_no_evil: removed it

2021-10-20 18:37 UTC, florianl commented
> Can you please check what's wrong?

I have checked the value `recordID` before assigning it with `recordID = r.Hits.Hits[0].Metadata.Recid`.
The check on the value I have added just before opening the PR :see_no_evil:  this is fixed now

2021-10-21 13:10 UTC, clelange approved these changes
Thanks, now it's working and looks good to me!

2021-10-21 13:10 UTC, merged